### ISSUE TITLE
icrush-style-loader添加scope错误

### ISSUE THREAD

**Issue by yelloxing** [yelloxing/iCrush#5]
原始代码：

```scss
 :hover,
 .active {
         background-image: url(../assets/images/switch@hover.png);
  }
```

结果：
```css
:hover, active[data-icrush-75525450]{
         background-image: url(../assets/images/switch@hover.png);
}
```

期望：
```css
:hover[data-icrush-75525450], active[data-icrush-75525450]{
         background-image: url(../assets/images/switch@hover.png);
}
```
